### ISSUE TITLE
[Enhancement] Support for constrained. trick

### ISSUE THREAD

**Issue by illuZion9999** [NotPrab/AntiDecompiler-Cleaner#2]
For the `DnSpyCrash2` used by Dotnetsafer, `constrained.` is, in addition to `unaligned`, an opcode that can be used as a hide method protection.
Maybe you should add it? I attached an UnpackMe with the contrained. hide method trick.
[UnpackMe - constrained. Opcode.exe.zip](https://github.com/NotPrab/AntiDecompiler-Cleaner/files/4687460/UnpackMe.-.constrained.Opcode.exe.zip)

**Comment by NotPrab** [comment]
Thanks i added it
