### ISSUE TITLE
Please add 32 bit compiled release

### ISSUE THREAD

**Issue by footballs** [NotPrab/AntiDecompiler-Cleaner#3]
I opened rar files and it says file is for 64 bit and I am using 32 bit.
Please add it for others. I am compiling it for me . Thanks.

**Comment by footballs** [comment]
Brother Does it supports anti-dnspy ? I checked it but it won't work against dnspy.

**Comment by NotPrab** [comment]
> 
> 
> Brother Does it supports anti-dnspy ? I checked it but it won't work against dnspy.

What do you mean by **anti-dnSpy** ? how is it works ? can u briefly explain ?

**Comment by footballs** [comment]
> What do you mean by **anti-dnSpy** ? how is it works ? can u briefly explain ?

A assembly that prevents from viewed using dnspy or ilspy. like this

![Capture](https://user-images.githubusercontent.com/70466231/98552562-6b0cd380-22c0-11eb-888c-017c457b9d78.PNG)

**Comment by NotPrab** [comment]
Added x32 compiled release thanks !
